USE project3_db

--INSERT NODA DATA
INSERT INTO NEIGHBORHOOD (ID, HOODNAME, ZIPCODE, BOUNDARYDESC, BOUNDARY_PHOTO, HOOD_VIBE, TRENDING_TOWARDS, COMING_SOON, ZID)
VALUES (1, 'NoDa', 28205, 'From Tryon to Plaza Rd & Sugar Creek to Matheson', '', 'Art, Nightlife', 'With the opening of the lightrail station in March of 2018 and the continued ground-breaking on new apartment homes, the nightlife in NoDa is not going anywhere anytime soon.', 'Wooden Robot Brewery [Early 2019]' 274696);

--INSERT PLAZA DATA
INSERT INTO NEIGHBORHOOD (ID, HOODNAME, ZIPCODE, BOUNDARYDESC, BOUNDARY_PHOTO, HOOD_VIBE, TRENDING_TOWARDS, COMING_SOON, ZID)
VALUES (2, 'Plaza Midwood');

--INSERT UPTOWN DATA
INSERT INTO NEIGHBORHOOD (ID, HOODNAME, ZIPCODE, BOUNDARYDESC, BOUNDARY_PHOTO, HOOD_VIBE, TRENDING_TOWARDS, COMING_SOON, ZID)
VALUES (3, 'Uptown', 28202, 'Inside the 277 loop');

--INSERT DILWORTH DATA
INSERT INTO NEIGHBORHOOD (ID, HOODNAME, ZIPCODE, BOUNDARYDESC, BOUNDARY_PHOTO, HOOD_VIBE, TRENDING_TOWARDS, COMING_SOON, ZID)
VALUES (4, 'Dilworth', 28203);

--INSERT SOUTH END DATA
INSERT INTO NEIGHBORHOOD (ID, HOODNAME, ZIPCODE, BOUNDARYDESC, BOUNDARY_PHOTO, HOOD_VIBE, TRENDING_TOWARDS, COMING_SOON, ZID)
VALUES (5, 'South End');